// import 'package:scribby_flutter_v2/functions/game_logic.dart';

List<Map<String, dynamic>> initialBoardState = [
  // ROW 1
  {"tileId": "1_1","row": 1,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "1_2","row": 1,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "1_3","row": 1,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "1_4","row": 1,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "1_5","row": 1,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "1_6","row": 1,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 2
  {"tileId": "2_1","row": 2,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "2_2","row": 2,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "2_3","row": 2,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "2_4","row": 2,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "2_5","row": 2,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "2_6","row": 2,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 3
  {"tileId": "3_1","row": 3,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "3_2","row": 3,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "3_3","row": 3,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "3_4","row": 3,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "3_5","row": 3,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "3_6","row": 3,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 4
  {"tileId": "4_1","row": 4,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "4_2","row": 4,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "4_3","row": 4,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "4_4","row": 4,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "4_5","row": 4,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "4_6","row": 4,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 5
  {"tileId": "5_1","row": 5,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "5_2","row": 5,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "5_3","row": 5,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "5_4","row": 5,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "5_5","row": 5,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "5_6","row": 5,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 6
  {"tileId": "6_1","row": 6,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "6_2","row": 6,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "6_3","row": 6,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "6_4","row": 6,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "6_5","row": 6,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "6_6","row": 6,"column": 6,"letter": "","active": false,"alive": true},
];

List<Map<String, dynamic>> alphabets = [
  {
    "language": "english",
    "alphabet": englishAlphabet,
  },
  {
    "language": "french",
    "alphabet": frenchAlphabet,
  },
];

// List<Map<String,dynamic>> initialRandomLetterState = [
//   {"letter" : "A", "type" : "vowel",      "points": 1,  "count": 86, "inPlay": 0},
//   {"letter" : "B", "type" : "consonant",  "points": 3,  "count": 24, "inPlay": 0},
//   {"letter" : "C", "type" : "consonant",  "points": 1,  "count": 33, "inPlay": 0},
//   {"letter" : "D", "type" : "consonant",  "points": 2,  "count": 39, "inPlay": 0},
//   {"letter" : "E", "type" : "vowel",      "points": 1,  "count": 111, "inPlay": 0},
//   {"letter" : "F", "type" : "consonant",  "points": 3,  "count": 17, "inPlay": 0},
//   {"letter" : "G", "type" : "consonant",  "points": 1,  "count": 27, "inPlay": 0},
//   {"letter" : "H", "type" : "consonant",  "points": 1,  "count": 27, "inPlay": 0},
//   {"letter" : "I", "type" : "vowel",      "points": 1,  "count": 64, "inPlay": 0},
//   {"letter" : "J", "type" : "consonant",  "points": 10, "count": 4, "inPlay": 0},
//   {"letter" : "K", "type" : "consonant",  "points": 1,  "count": 21, "inPlay": 0},
//   {"letter" : "L", "type" : "consonant",  "points": 2,  "count": 54, "inPlay": 0},
//   {"letter" : "M", "type" : "consonant",  "points": 1,  "count": 30, "inPlay": 0},
//   {"letter" : "N", "type" : "consonant",  "points": 2,  "count": 49, "inPlay": 0},
//   {"letter" : "O", "type" : "vowel",      "points": 1,  "count": 64, "inPlay": 0},
//   {"letter" : "P", "type" : "consonant",  "points": 1,  "count": 29, "inPlay": 0},
//   {"letter" : "Q", "type" : "consonant",  "points": 10, "count": 2, "inPlay": 0},
//   {"letter" : "R", "type" : "consonant",  "points": 1,  "count": 67, "inPlay": 0},
//   {"letter" : "S", "type" : "consonant",  "points": 1,  "count": 95, "inPlay": 0},
//   {"letter" : "T", "type" : "consonant",  "points": 2,  "count": 50, "inPlay": 0},
//   {"letter" : "U", "type" : "vowel",      "points": 2,  "count": 21, "inPlay": 0}, // count originally 41
//   {"letter" : "V", "type" : "consonant",  "points": 2,  "count": 11, "inPlay": 0},
//   {"letter" : "W", "type" : "consonant",  "points": 2,  "count": 15, "inPlay": 0},
//   {"letter" : "X", "type" : "consonant",  "points": 5,  "count": 4, "inPlay": 0},
//   {"letter" : "Y", "type" : "consonant",  "points": 5,  "count": 27, "inPlay": 0},
//   {"letter" : "Z", "type" : "consonant",  "points": 9,  "count": 7, "inPlay": 0},
// ];

// List<Map<String,dynamic>> initialRandomLetterState = getInitialRandomLetterState()

// List<Map<String,dynamic>> startingAlphabetState = GameLogic().generateStartingStates(initialRandomLetterState, initialBoardState, [])['startingAlphabet'];
// List<String> randomLetterListState = GameLogic().generateStartingStates(initialRandomLetterState, initialBoardState, [])['startingRandomLetterList'];
// List<Map<String,dynamic>> startingTileState = GameLogic().generateStartingStates(initialRandomLetterState, initialBoardState, [])['startingTileState'];
// List<String> randomLetterListState = [];

List<Map<String, dynamic>> turnSummaryState = [];

List<Map<String, dynamic>> stringCombinations = [
  {'len': 3,'arr': ['1_1', '1_2', '1_3'],'axis': 'row'  },
  {'len': 3,'arr': ['1_2', '1_3', '1_4'],'axis': 'row'  },
  {'len': 3,'arr': ['1_3', '1_4', '1_5'],'axis': 'row'  },
  {'len': 3,'arr': ['1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 3,'arr': ['2_1', '2_2', '2_3'],'axis': 'row'  },
  {'len': 3,'arr': ['2_2', '2_3', '2_4'],'axis': 'row'  },
  {'len': 3,'arr': ['2_3', '2_4', '2_5'],'axis': 'row'  },
  {'len': 3,'arr': ['2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 3,'arr': ['3_1', '3_2', '3_3'],'axis': 'row'  },
  {'len': 3,'arr': ['3_2', '3_3', '3_4'],'axis': 'row'  },
  {'len': 3,'arr': ['3_3', '3_4', '3_5'],'axis': 'row'  },
  {'len': 3,'arr': ['3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 3,'arr': ['4_1', '4_2', '4_3'],'axis': 'row'  },
  {'len': 3,'arr': ['4_2', '4_3', '4_4'],'axis': 'row'  },
  {'len': 3,'arr': ['4_3', '4_4', '4_5'],'axis': 'row'  },
  {'len': 3,'arr': ['4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 3,'arr': ['5_1', '5_2', '5_3'],'axis': 'row'  },
  {'len': 3,'arr': ['5_2', '5_3', '5_4'],'axis': 'row'  },
  {'len': 3,'arr': ['5_3', '5_4', '5_5'],'axis': 'row'  },
  {'len': 3,'arr': ['5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 3,'arr': ['6_1', '6_2', '6_3'],'axis': 'row'  },
  {'len': 3,'arr': ['6_2', '6_3', '6_4'],'axis': 'row'  },
  {'len': 3,'arr': ['6_3', '6_4', '6_5'],'axis': 'row'  },
  {'len': 3,'arr': ['6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 4,'arr': ['1_1', '1_2', '1_3', '1_4'],'axis': 'row'  },
  {'len': 4,'arr': ['1_2', '1_3', '1_4', '1_5'],'axis': 'row'  },
  {'len': 4,'arr': ['1_3', '1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 4,'arr': ['2_1', '2_2', '2_3', '2_4'],'axis': 'row'  },
  {'len': 4,'arr': ['2_2', '2_3', '2_4', '2_5'],'axis': 'row'  },
  {'len': 4,'arr': ['2_3', '2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 4,'arr': ['3_1', '3_2', '3_3', '3_4'],'axis': 'row'  },
  {'len': 4,'arr': ['3_2', '3_3', '3_4', '3_5'],'axis': 'row'  },
  {'len': 4,'arr': ['3_3', '3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 4,'arr': ['4_1', '4_2', '4_3', '4_4'],'axis': 'row'  },
  {'len': 4,'arr': ['4_2', '4_3', '4_4', '4_5'],'axis': 'row'  },
  {'len': 4,'arr': ['4_3', '4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 4,'arr': ['5_1', '5_2', '5_3', '5_4'],'axis': 'row'  },
  {'len': 4,'arr': ['5_2', '5_3', '5_4', '5_5'],'axis': 'row'  },
  {'len': 4,'arr': ['5_3', '5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 4,'arr': ['6_1', '6_2', '6_3', '6_4'],'axis': 'row'  },
  {'len': 4,'arr': ['6_2', '6_3', '6_4', '6_5'],'axis': 'row'  },
  {'len': 4,'arr': ['6_3', '6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 5,'arr': ['1_1', '1_2', '1_3', '1_4', '1_5'],'axis': 'row'  },
  {'len': 5,'arr': ['1_2', '1_3', '1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 5,'arr': ['2_1', '2_2', '2_3', '2_4', '2_5'],'axis': 'row'  },
  {'len': 5,'arr': ['2_2', '2_3', '2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 5,'arr': ['3_1', '3_2', '3_3', '3_4', '3_5'],'axis': 'row'  },
  {'len': 5,'arr': ['3_2', '3_3', '3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 5,'arr': ['4_1', '4_2', '4_3', '4_4', '4_5'],'axis': 'row'  },
  {'len': 5,'arr': ['4_2', '4_3', '4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 5,'arr': ['5_1', '5_2', '5_3', '5_4', '5_5'],'axis': 'row'  },
  {'len': 5,'arr': ['5_2', '5_3', '5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 5,'arr': ['6_1', '6_2', '6_3', '6_4', '6_5'],'axis': 'row'  },
  {'len': 5,'arr': ['6_2', '6_3', '6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 6,'arr': ['1_1', '1_2', '1_3', '1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 6,'arr': ['2_1', '2_2', '2_3', '2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 6,'arr': ['3_1', '3_2', '3_3', '3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 6,'arr': ['4_1', '4_2', '4_3', '4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 6,'arr': ['5_1', '5_2', '5_3', '5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 6,'arr': ['6_1', '6_2', '6_3', '6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 3,'arr': ['1_1', '2_1', '3_1'],'axis': 'column'  },
  {'len': 3,'arr': ['1_2', '2_2', '3_2'],'axis': 'column'  },
  {'len': 3,'arr': ['1_3', '2_3', '3_3'],'axis': 'column'  },
  {'len': 3,'arr': ['1_4', '2_4', '3_4'],'axis': 'column'  },
  {'len': 3,'arr': ['1_5', '2_5', '3_5'],'axis': 'column'  },
  {'len': 3,'arr': ['1_6', '2_6', '3_6'],'axis': 'column'  },
  {'len': 3,'arr': ['2_1', '3_1', '4_1'],'axis': 'column'  },
  {'len': 3,'arr': ['2_2', '3_2', '4_2'],'axis': 'column'  },
  {'len': 3,'arr': ['2_3', '3_3', '4_3'],'axis': 'column'  },
  {'len': 3,'arr': ['2_4', '3_4', '4_4'],'axis': 'column'  },
  {'len': 3,'arr': ['2_5', '3_5', '4_5'],'axis': 'column'  },
  {'len': 3,'arr': ['2_6', '3_6', '4_6'],'axis': 'column'  },
  {'len': 3,'arr': ['3_1', '4_1', '5_1'],'axis': 'column'  },
  {'len': 3,'arr': ['3_2', '4_2', '5_2'],'axis': 'column'  },
  {'len': 3,'arr': ['3_3', '4_3', '5_3'],'axis': 'column'  },
  {'len': 3,'arr': ['3_4', '4_4', '5_4'],'axis': 'column'  },
  {'len': 3,'arr': ['3_5', '4_5', '5_5'],'axis': 'column'  },
  {'len': 3,'arr': ['3_6', '4_6', '5_6'],'axis': 'column'  },
  {'len': 3,'arr': ['4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 3,'arr': ['4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 3,'arr': ['4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 3,'arr': ['4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 3,'arr': ['4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 3,'arr': ['4_6', '5_6', '6_6'],'axis': 'column'  },
  {'len': 4,'arr': ['1_1', '2_1', '3_1', '4_1'],'axis': 'column'  },
  {'len': 4,'arr': ['1_2', '2_2', '3_2', '4_2'],'axis': 'column'  },
  {'len': 4,'arr': ['1_3', '2_3', '3_3', '4_3'],'axis': 'column'  },
  {'len': 4,'arr': ['1_4', '2_4', '3_4', '4_4'],'axis': 'column'  },
  {'len': 4,'arr': ['1_5', '2_5', '3_5', '4_5'],'axis': 'column'  },
  {'len': 4,'arr': ['1_6', '2_6', '3_6', '4_6'],'axis': 'column'  },
  {'len': 4,'arr': ['2_1', '3_1', '4_1', '5_1'],'axis': 'column'  },
  {'len': 4,'arr': ['2_2', '3_2', '4_2', '5_2'],'axis': 'column'  },
  {'len': 4,'arr': ['2_3', '3_3', '4_3', '5_3'],'axis': 'column'  },
  {'len': 4,'arr': ['2_4', '3_4', '4_4', '5_4'],'axis': 'column'  },
  {'len': 4,'arr': ['2_5', '3_5', '4_5', '5_5'],'axis': 'column'  },
  {'len': 4,'arr': ['2_6', '3_6', '4_6', '5_6'],'axis': 'column'  },
  {'len': 4,'arr': ['3_1', '4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 4,'arr': ['3_2', '4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 4,'arr': ['3_3', '4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 4,'arr': ['3_4', '4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 4,'arr': ['3_5', '4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 4,'arr': ['3_6', '4_6', '5_6', '6_6'],'axis': 'column'  },
  {'len': 5,'arr': ['1_1', '2_1', '3_1', '4_1', '5_1'],'axis': 'column'  },
  {'len': 5,'arr': ['1_2', '2_2', '3_2', '4_2', '5_2'],'axis': 'column'  },
  {'len': 5,'arr': ['1_3', '2_3', '3_3', '4_3', '5_3'],'axis': 'column'  },
  {'len': 5,'arr': ['1_4', '2_4', '3_4', '4_4', '5_4'],'axis': 'column'  },
  {'len': 5,'arr': ['1_5', '2_5', '3_5', '4_5', '5_5'],'axis': 'column'  },
  {'len': 5,'arr': ['1_6', '2_6', '3_6', '4_6', '5_6'],'axis': 'column'  },
  {'len': 5,'arr': ['2_1', '3_1', '4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 5,'arr': ['2_2', '3_2', '4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 5,'arr': ['2_3', '3_3', '4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 5,'arr': ['2_4', '3_4', '4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 5,'arr': ['2_5', '3_5', '4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 5,'arr': ['2_6', '3_6', '4_6', '5_6', '6_6'],'axis': 'column'  },
  {'len': 6,'arr': ['1_1', '2_1', '3_1', '4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 6,'arr': ['1_2', '2_2', '3_2', '4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 6,'arr': ['1_3', '2_3', '3_3', '4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 6,'arr': ['1_4', '2_4', '3_4', '4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 6,'arr': ['1_5', '2_5', '3_5', '4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 6,'arr': ['1_6', '2_6', '3_6', '4_6', '5_6', '6_6'],'axis': 'column'  },
];

List<Map<String, dynamic>> demoBoardState_1 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "letter_01", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "letter_02", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_2 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "letter_02", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "letter_03", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "letter_01", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_3 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "letter_03", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "letter_04", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "letter_01", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "letter_02", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_4 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "letter_04", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "letter_05", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "letter_01", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "letter_02", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "letter_03", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_5 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "letter_05", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "letter_06", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "letter_01", "active": true},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "letter_04", "active": true},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "letter_02", "active": true},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "letter_03", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_6 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "letter_05", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "letter_06", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "letter_03", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];




final Map<String,dynamic> demoStateDynamicLetters = {
  'english': {
    'letter_01' : 'A',
    'letter_02' : 'K',
    'letter_03' : 'U',
    'letter_04' : 'S',
    'letter_05' : 'E',
    'letter_06' : 'N',
    'WORD' : 'ASK',
  },

  'french': {
    'letter_01' : 'E',
    'letter_02' : 'U',
    'letter_03' : 'V',
    'letter_04' : 'A',
    'letter_05' : 'R',
    'letter_06' : 'S',
    'WORD' : 'EAU',
  },  

  'spanish': {
    'letter_01' : 'G',
    'letter_02' : 'L',
    'letter_03' : 'S',
    'letter_04' : 'O',
    'letter_05' : 'B',
    'letter_06' : 'T',
    'WORD' : 'GOL',
  },  

  'german': {
    'letter_01' : 'I',
    'letter_02' : 'H',
    'letter_03' : 'T',
    'letter_04' : 'C',
    'letter_05' : 'W',
    'letter_06' : 'R',
    'WORD' : 'ICH',
  },  

  'italian': {
    'letter_01' : 'O',
    'letter_02' : 'A',
    'letter_03' : 'Z',
    'letter_04' : 'R',
    'letter_05' : 'I',
    'letter_06' : 'B',
    'WORD' : 'ORA',
  },  

  'portuguese': {
    'letter_01' : 'B',
    'letter_02' : 'M',
    'letter_03' : 'L',
    'letter_04' : 'O',
    'letter_05' : 'J',
    'letter_06' : 'A',
    'WORD' : 'BOM',
  },  

  'greek': {
    'letter_01' : 'Ε',
    'letter_02' : 'Ρ',
    'letter_03' : 'Ζ',
    'letter_04' : 'Α',
    'letter_05' : 'Τ',
    'letter_06' : 'Π',
    'WORD' : 'ΕΑΡ',
  }, 

  'dutch': {
    'letter_01' : 'S',
    'letter_02' : 'T',
    'letter_03' : 'H',
    'letter_04' : 'E',
    'letter_05' : 'X',
    'letter_06' : 'G',
    'WORD' : 'SET',
  },              
};



List<Map<String, dynamic>> englishAlphabet = [
  {"letter": "A", "type": "vowel", "points": 1, "count": 86, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 24, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 1, "count": 33, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 39, "inPlay": 0},
  {"letter": "E", "type": "vowel", "points": 1, "count": 111, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 3, "count": 17, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 1, "count": 27, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 1, "count": 27, "inPlay": 0},
  {"letter": "I", "type": "vowel", "points": 1, "count": 64, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 10, "count": 4, "inPlay": 0},
  {"letter": "K", "type": "consonant", "points": 1, "count": 21, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 2, "count": 54, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 1, "count": 30, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 2, "count": 49, "inPlay": 0},
  {"letter": "O", "type": "vowel", "points": 1, "count": 64, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 1, "count": 29, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 10, "count": 2, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 67, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 95, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 2, "count": 50, "inPlay": 0},
  {"letter": "U", "type": "vowel",      "points": 2,"count": 21,  "inPlay": 0}, // count originally 41
  {"letter": "V", "type": "consonant", "points": 2, "count": 11, "inPlay": 0},
  {"letter": "W", "type": "consonant", "points": 2, "count": 15, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 5, "count": 4, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 5, "count": 27, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 9, "count": 7, "inPlay": 0},
];

List<Map<String, dynamic>> frenchAlphabet = [
  {"letter": "A", "type": "vowel", "points": 1, "count": 90, "inPlay": 0},
  {"letter": "À", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Â", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 20, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 1, "count": 20, "inPlay": 0},
  {"letter": "Ç", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 30, "inPlay": 0},
  {"letter": "E", "type": "vowel", "points": 1, "count": 150, "inPlay": 0},
  {"letter": "È", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "É", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ê", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ë", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 4, "count": 20, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 2, "count": 20, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 4, "count": 20, "inPlay": 0},
  {"letter": "Î", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ï", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "I", "type": "vowel", "points": 1, "count": 80, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 8, "count": 10, "inPlay": 0},
  {"letter": "K", "type": "consonant", "points": 10, "count": 10, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 1, "count": 50, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 2, "count": 30, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "O", "type": "vowel", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "Ô", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 3, "count": 20, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 8, "count": 3, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "U","type": "vowel","points": 1,"count": 60,"inPlay": 0},
  {"letter": "U","type": "vowel","points": 10,"count": 1,"inPlay": 0},
  {"letter": "U","type": "vowel","points": 10,"count": 1,"inPlay": 0},
  {"letter": "U","type": "vowel","points": 10,"count": 1,"inPlay": 0}, // count originally 41
  {"letter": "V", "type": "consonant", "points": 4, "count": 20, "inPlay": 0},
  {"letter": "W", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
];

List<Map<String, dynamic>> spanishAlphabet = [
  {"letter": "A", "type": "vowel", "points": 1, "count": 12, "inPlay": 0},
  {"letter": "Á", "type": "vowel", "points": 10, "count": 2, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 3, "count": 4, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "E", "type": "vowel", "points": 1, "count": 12, "inPlay": 0},
  {"letter": "É", "type": "vowel", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 4, "count": 1, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 2, "count": 2, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "I", "type": "vowel", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "Í", "type": "vowel", "points": 10, "count": 2, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 1, "count": 4, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 1, "count": 5, "inPlay": 0},
  {"letter": "Ñ", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "O", "type": "vowel", "points": 1, "count": 9, "inPlay": 0},
  {"letter": "Ó", "type": "vowel", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 5, "count": 1, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 5, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 1, "count": 4, "inPlay": 0},
  {"letter": "U","type": "vowel","points": 1,"count": 5,"inPlay": 0}, 
  {"letter": "Ú","type": "vowel","points": 10,"count": 1,"inPlay": 0},
  {"letter": "Ü","type": "vowel","points": 10,"count": 1,"inPlay": 0}, 
  {"letter": "X", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 4, "count": 1, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
];


List<Map<String, dynamic>> germanAlphabet = [
  {"letter": "A", "type": "consonant", "points": 1, "count": 12, "inPlay": 0},
  {"letter": "Ä", "type": "consonant", "points": 6, "count": 2, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 4, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 4, "count": 4, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 1, "count": 7, "inPlay": 0},
  {"letter": "E", "type": "consonant", "points": 1, "count": 29, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 4, "count": 4, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 2, "count": 8, "inPlay": 0},
  {"letter": "I", "type": "consonant", "points": 1, "count": 11, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 6, "count": 2, "inPlay": 0},
  {"letter": "K", "type": "consonant", "points": 4, "count": 4, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 3, "count": 8, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 1, "count": 17, "inPlay": 0},
  {"letter": "O", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "Ö", "type": "consonant", "points": 8, "count": 2, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 4, "count": 3, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 10, "count": 2, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 11, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 14, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 1, "count": 12, "inPlay": 0},
  {"letter": "U", "type": "consonant", "points": 1, "count": 10, "inPlay": 0},
  {"letter": "Ü", "type": "consonant", "points": 6, "count": 2, "inPlay": 0},
  {"letter": "V", "type": "consonant", "points": 6, "count": 2, "inPlay": 0},
  {"letter": "W", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 8, "count": 2, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 10, "count": 2, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},

];
List<Map<String, dynamic>> italianAlphabet = [
  {"letter": "O", "type": "consonant", "points": 1, "count": 15, "inPlay": 0},
  {"letter": "A", "type": "consonant", "points": 1, "count": 14, "inPlay": 0},
  {"letter": "I", "type": "consonant", "points": 1, "count": 12, "inPlay": 0},
  {"letter": "E", "type": "consonant", "points": 1, "count": 11, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 2, "count": 6, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 3, "count": 5, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 3, "count": 5, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 3, "count": 5, "inPlay": 0},
  {"letter": "U", "type": "consonant", "points": 3, "count": 5, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 5, "count": 3, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 5, "count": 3, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 5, "count": 3, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 5, "count": 3, "inPlay": 0},
  {"letter": "V", "type": "consonant", "points": 5, "count": 3, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 8, "count": 2, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 8, "count": 2, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 8, "count": 2, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},

];
List<Map<String, dynamic>> greekAlphabet = [
  {"letter": "Α", "type": "consonant", "points": 1, "count": 12, "inPlay": 0},
  {"letter": "Ο", "type": "consonant", "points": 1, "count": 9, "inPlay": 0},
  {"letter": "Ε", "type": "consonant", "points": 1, "count": 8, "inPlay": 0},
  {"letter": "Ι", "type": "consonant", "points": 1, "count": 8, "inPlay": 0},
  {"letter": "Τ", "type": "consonant", "points": 1, "count": 8, "inPlay": 0},
  {"letter": "Η", "type": "consonant", "points": 1, "count": 7, "inPlay": 0},
  {"letter": "Σ", "type": "consonant", "points": 1, "count": 7, "inPlay": 0},
  {"letter": "Ν", "type": "consonant", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "Ρ", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "Κ", "type": "consonant", "points": 2, "count": 4, "inPlay": 0},
  {"letter": "Π", "type": "consonant", "points": 2, "count": 4, "inPlay": 0},
  {"letter": "Υ", "type": "consonant", "points": 2, "count": 4, "inPlay": 0},
  {"letter": "Λ", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "Μ", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "Ω", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "Γ", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "Δ", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "Β", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Φ", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Χ", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Ζ", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Θ", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ξ", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ψ", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},


];
List<Map<String, dynamic>> portugueseAlphabet = [
  {"letter": "A", "type": "consonant", "points": 1, "count": 14, "inPlay": 0},
  {"letter": "E", "type": "consonant", "points": 1, "count": 11, "inPlay": 0},
  {"letter": "I", "type": "consonant", "points": 1, "count": 10, "inPlay": 0},
  {"letter": "O", "type": "consonant", "points": 1, "count": 10, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 8, "inPlay": 0},
  {"letter": "U", "type": "consonant", "points": 1, "count": 7, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 1, "count": 5, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 2, "count": 4, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 2, "count": 4, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 3, "count": 4, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "Ç", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "V", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 5, "count": 2, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 6, "count": 1, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Á", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "É", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Í", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ó", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ú", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Â", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ê", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ô", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Ã", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "Õ", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},

];
List<Map<String, dynamic>> dutchAlphabet = [
  {"letter": "A", "type": "consonant", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "Ä", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 5, "count": 2, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "E", "type": "consonant", "points": 1, "count": 18, "inPlay": 0},
  {"letter": "Ë", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "É", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "È", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "I", "type": "consonant", "points": 1, "count": 4, "inPlay": 0},
  {"letter": "Ï", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "K", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 3, "count": 3, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 1, "count": 10, "inPlay": 0},
  {"letter": "O", "type": "consonant", "points": 1, "count": 6, "inPlay": 0},
  {"letter": "Ö", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 3, "count": 2, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 2, "count": 5, "inPlay": 0},
  {"letter": "U", "type": "consonant", "points": 4, "count": 3, "inPlay": 0},
  {"letter": "Ü", "type": "consonant", "points": 10, "count": 1, "inPlay": 0},
  {"letter": "V", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},
  {"letter": "W", "type": "consonant", "points": 5, "count": 2, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 8, "count": 1, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 4, "count": 2, "inPlay": 0},

];










List<Map<String, dynamic>> tutorialBoard_1 = [
  // // Random Letters
  // {"tileId" : "0_0", "row":0 , "column":0 , "letter" : "E", "active": false},
  // {"tileId" : "0_1", "row":0 , "column":1 , "letter" : "N", "active": false},
  // Board
  {"index": 0,"tileId": "1_1","row": 1,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 1,"tileId": "1_2","row": 1,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 2,"tileId": "1_3","row": 1,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 3,"tileId": "1_4","row": 1,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 4,"tileId": "1_5","row": 1,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 5,"tileId": "1_6","row": 1,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 6,"tileId": "2_1","row": 2,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 7,"tileId": "2_2","row": 2,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 8,"tileId": "2_3","row": 2,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 9,"tileId": "2_4","row": 2,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 10,"tileId": "2_5","row": 2,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 11,"tileId": "2_6","row": 2,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 12,"tileId": "3_1","row": 3,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 13,"tileId": "3_2","row": 3,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 14,"tileId": "3_3","row": 3,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 15,"tileId": "3_4","row": 3,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 16,"tileId": "3_5","row": 3,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 17,"tileId": "3_6","row": 3,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 18,"tileId": "4_1","row": 4,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 19,"tileId": "4_2","row": 4,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 20,"tileId": "4_3","row": 4,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 21,"tileId": "4_4","row": 4,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 22,"tileId": "4_5","row": 4,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 23,"tileId": "4_6","row": 4,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 24,"tileId": "5_1","row": 5,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 25,"tileId": "5_2","row": 5,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 26,"tileId": "5_3","row": 5,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 27,"tileId": "5_4","row": 5,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 28,"tileId": "5_5","row": 5,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 29,"tileId": "5_6","row": 5,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 30,"tileId": "6_1","row": 6,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 31,"tileId": "6_2","row": 6,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 32,"tileId": "6_3","row": 6,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 33,"tileId": "6_4","row": 6,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 34,"tileId": "6_5","row": 6,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 35,"tileId": "6_6","row": 6,"column": 6,"letter": "","active": false, "alive": true  },
];




Map<String,dynamic> tutorialLetters = {
  
    "english": {
      "letter_00" : "",
      "letter_01" : "T",
      "letter_02" : "L",
      "letter_03" : "A",
      "letter_04" : "C",
      "letter_05" : "A",
      "letter_06" : "E",
      "letter_07" : "S",
      "letter_08" : "P",
      "letter_09" : "W",
      "letter_10" : "T",
      "letter_11" : "A",
      "letter_12" : "G",
      "letter_13" : "B",
      "letter_14" : "P",
      "letter_15" : "N",
      "letter_16" : "S",
      "letter_17" : "H",
      "letter_18" : "I",   
      "letter_19" : "N",
      "letter_20" : "T",
      "letter_21" : "U",
      "letter_22" : "R",
      "letter_23" : "Z",       
      "letter_24" : "E",
      "letter_25" : "Y",     
      "letter_26" : "W",     
      "letter_27" : "O",                  
    } ,
  
    "french": {
      "letter_00" : "",
      "letter_01" : "U",
      "letter_02" : "R",
      "letter_03" : "A",
      "letter_04" : "E",
      "letter_05" : "E",
      "letter_06" : "E",
      "letter_07" : "P",
      "letter_08" : "L",
      "letter_09" : "J",
      "letter_10" : "N",
      "letter_11" : "Z",
      "letter_12" : "R",
      "letter_13" : "M",
      "letter_14" : "X",
      "letter_15" : "N",
      "letter_16" : "U",
      "letter_17" : "L",
      "letter_18" : "I",
      "letter_19" : "T",
      "letter_20" : "E",
      "letter_21" : "I",
      "letter_22" : "A",
      "letter_23" : "E",
      "letter_24" : "S",
      "letter_25" : "A",
      "letter_26" : "K",
      "letter_27" : "Q",  
    },
    "spanish": {
      "letter_00" : "",
      "letter_01" : "L",
      "letter_02" : "A",
      "letter_03" : "O",
      "letter_04" : "G",
      "letter_05" : "I",
      "letter_06" : "R",
      "letter_07" : "P",
      "letter_08" : "R",
      "letter_09" : "M",
      "letter_10" : "S",
      "letter_11" : "O",
      "letter_12" : "A",
      "letter_13" : "V",
      "letter_14" : "A",
      "letter_15" : "E",
      "letter_16" : "R",
      "letter_17" : "T",
      "letter_18" : "M",
      "letter_19" : "S",
      "letter_20" : "A",
      "letter_21" : "Y",
      "letter_22" : "I",
      "letter_23" : "P",
      "letter_24" : "M",
      "letter_25" : "I",
      "letter_26" : "R",
      "letter_27" : "A",
               
    },
    "german": {
      "letter_00" : "",
      "letter_01" : "S",
      "letter_02" : "R",
      "letter_03" : "E",
      "letter_04" : "C",
      "letter_05" : "D",
      "letter_06" : "N",
      "letter_07" : "F",
      "letter_08" : "L",
      "letter_09" : "A",
      "letter_10" : "Ü",
      "letter_11" : "B",
      "letter_12" : "E",
      "letter_13" : "A",
      "letter_14" : "R",
      "letter_15" : "A",
      "letter_16" : "E",
      "letter_17" : "T",
      "letter_18" : "G",
      "letter_19" : "O",
      "letter_20" : "L",
      "letter_21" : "E",
      "letter_22" : "O",
      "letter_23" : "F",
      "letter_24" : "A",
      "letter_25" : "D",
      "letter_26" : "E",
      "letter_27" : "R",
                  
    },
    "italian": {
      "letter_00" : "",
      "letter_01" : "L",
      "letter_02" : "I",
      "letter_03" : "I",
      "letter_04" : "E",
      "letter_05" : "A",
      "letter_06" : "O",
      "letter_07" : "R",
      "letter_08" : "A",
      "letter_09" : "C",
      "letter_10" : "V",
      "letter_11" : "I",
      "letter_12" : "I",
      "letter_13" : "P",
      "letter_14" : "I",
      "letter_15" : "N",
      "letter_16" : "P",
      "letter_17" : "U",
      "letter_18" : "G",
      "letter_19" : "O",
      "letter_20" : "O",
      "letter_21" : "A",
      "letter_22" : "G",
      "letter_23" : "R",
      "letter_24" : "C",
      "letter_25" : "A",
      "letter_26" : "P",
      "letter_27" : "I",
                  
    },
    "portuguese": {
      "letter_00" : "",
      "letter_01" : "R",
      "letter_02" : "A",
      "letter_03" : "I",
      "letter_04" : "T",
      "letter_05" : "A",
      "letter_06" : "S",
      "letter_07" : "T",
      "letter_08" : "E",
      "letter_09" : "P",
      "letter_10" : "S",
      "letter_11" : "A",
      "letter_12" : "O",
      "letter_13" : "V",
      "letter_14" : "A",
      "letter_15" : "B",
      "letter_16" : "R",
      "letter_17" : "A",
      "letter_18" : "T",
      "letter_19" : "I",
      "letter_20" : "E",
      "letter_21" : "Í",
      "letter_22" : "X",
      "letter_23" : "T",
      "letter_24" : "P",
      "letter_25" : "A",
      "letter_26" : "R",
      "letter_27" : "A",
                   
    },
    "greek": {
      "letter_00" : "",
      "letter_01" : "Ε",
      "letter_02" : "Ω",
      "letter_03" : "Ρ",
      "letter_04" : "Ο",
      "letter_05" : "Ε",
      "letter_06" : "Σ",
      "letter_07" : "Σ",
      "letter_08" : "Κ",
      "letter_09" : "Μ",
      "letter_10" : "Α",
      "letter_11" : "Π",
      "letter_12" : "Ο",
      "letter_13" : "Ο",
      "letter_14" : "Ω",
      "letter_15" : "Ψ",
      "letter_16" : "Σ",
      "letter_17" : "Α",
      "letter_18" : "Ρ",
      "letter_19" : "Α",
      "letter_20" : "Ε",
      "letter_21" : "Ω",
      "letter_22" : "Υ",
      "letter_23" : "Σ",
      "letter_24" : "Μ",
      "letter_25" : "Ε",
      "letter_26" : "Σ",
      "letter_27" : "Ω",
                          
    },
    "dutch": {
      "letter_00" : "",
      "letter_01" : "S",
      "letter_02" : "G",
      "letter_03" : "A",
      "letter_04" : "T",
      "letter_05" : "A",
      "letter_06" : "N",
      "letter_07" : "A",
      "letter_08" : "A",
      "letter_09" : "G",
      "letter_010" : "B",
      "letter_011" : "A",
      "letter_012" : "E",
      "letter_013" : "J",
      "letter_014" : "G",
      "letter_015" : "E",
      "letter_016" : "L",
      "letter_017" : "Z",
      "letter_018" : "D",
      "letter_019" : "N",
      "letter_20" : "E",
      "letter_21" : "L",
      "letter_22" : "B",
      "letter_23" : "A",
      "letter_24" : "G",
      "letter_25" : "A",
      "letter_26" : "L",
      "letter_27" : "G",
                      
    },            
};

Map<String,dynamic> tutorialWords = {
  
    "english": {
      "word_1": "CAT",
      "word_2": "WAS",
      "word_3": "ASP",
      "word_4": "WASP",
      "word_5": "HUN",
      "word_6": "TEA",
      "word_7": "BEG",
      "word_8": "PRINT",
      "word_9": "SPRINT", 
    } ,
  
    "french": {
      "word_1": "EAU",
      "word_2": "JEU",
      "word_3": "EUX",
      "word_4": "JEUX",
      "word_5": "LIT",
      "word_6": "NEZ",
      "word_7": "MER",
      "word_8": "PLAINE",
      "word_9": "LAINE", 
    },
    "spanish": {
      "word_1": "GOL",
      "word_2": "MIR",
      "word_3": "IRA",
      "word_4": "MIRA",
      "word_5": "TEA",
      "word_6": "SOY",
      "word_7": "VOS",
      "word_8": "PRIMAR",
      "word_9": "PRIMA", 

            
    },
    "german": {
      "word_1": "CES",
      "word_2": "ADE",
      "word_3": "DER",
      "word_4": "ADER",
      "word_5": "TAL",
      "word_6": "ÜBE",
      "word_7": "ABO",
      "word_8": "FLOGEN",
      "word_9": "LOGEN",                  
    },
  



    "italian": {
      "word_1": "EIL",
      "word_2": "CAP",
      "word_3": "API",
      "word_4": "CAPI",
      "word_5": "UNO",
      "word_6": "VIA",
      "word_7": "PIO",
      "word_8": "RAGGIO",
      "word_9": "AGGIO", 


    },
    "portuguese": {
      "word_1": "TIR",
      "word_2": "PAR",
      "word_3": "ARA",
      "word_4": "PARA",
      "word_5": "ABE",
      "word_6": "SAÍ",
      "word_7": "VAI",
      "word_8": "TEXTOS",
      "word_9": "TEXTO",        
    },
    "greek": {
      "word_1": "ΟΡΕ",
      "word_2": "ΜΕΣ",
      "word_3": "ΕΣΩ",
      "word_4": "ΜΕΣΩ",
      "word_5": "ΑΨΕ",
      "word_6": "ΑΠΩ",
      "word_7": "ΟΠΑ",
      "word_8": "ΣΚΥΡΟΣ",
      "word_9": "ΚΥΡΟΣ",                     
    },   
    "dutch": {
      "word_1": "TAS",
      "word_2": "GAL",
      "word_3": "ALG",
      "word_4": "GALG",
      "word_5": "ZEE",
      "word_6": "BAL",
      "word_7": "JAN",
      "word_8": "AARDEN",
      "word_9": "AARDE", 
                     
    },            
};

Map<String,dynamic> tutorialPoints = {
  "english": {
    "points": {"points_0": "0", "points_1": "4", "points_2": "40", "points_3": "50", "points_4": "158", "points_5": "462",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints": {"nPts_0" : "0", "nPts_1" : "4","nPts_2" : "36","nPts_3" : "10","nPts_4" : "108","nPts_5" : "304",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },

  "french": {
    "points":   {"points_0":  "0",  "points_1": "3",  "points_2": "129",   "points_3": "135",   "points_4": "279",   "points_5": "551",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "3",   "nPts_2" :  "126",   "nPts_3" :  "6",   "nPts_4" :  "144",   "nPts_5" : "272",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },
  "spanish": {
    "points":   {"points_0":  "0",  "points_1": "4",   "points_2": "46",   "points_3": "52",   "points_4": "172",   "points_5": "556",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "4",   "nPts_2" :  "42",   "nPts_3" :  "6",   "nPts_4" :  "120",   "nPts_5" : "384",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },  
  "german": {
    "points":   {"points_0":  "0",  "points_1": "6",   "points_2": "36",   "points_3": "44",   "points_4": "196",   "points_5": "612",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "6",   "nPts_2" :  "30",   "nPts_3" :  "8",   "nPts_4" :  "152",   "nPts_5" : "416",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },  
  "italian": {
    "points":   {"points_0":  "0",  "points_1": "5",   "points_2": "77",   "points_3": "91",   "points_4": "231",   "points_5": "1039",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "5",   "nPts_2" :  "72",   "nPts_3" :  "14",   "nPts_4" :  "140",   "nPts_5" : "808",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },  
  "portuguese": {
    "points":   {"points_0":  "0",  "points_1": "3",   "points_2": "39",   "points_3": "49",   "points_4": "217",   "points_5": "721",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "3",   "nPts_2" :  "36",   "nPts_3" :  "10",   "nPts_4" :  "168",   "nPts_5" : "504",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },  
  "greek": {
    "points":   {"points_0":  "0",  "points_1": "4",   "points_2": "58",   "points_3": "82",   "points_4": "178",   "points_5": "522",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "4",   "nPts_2" :  "54",   "nPts_3" :  "24",   "nPts_4" :  "96",   "nPts_5" : "344",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },
  "dutch": {
    "points":   {"points_0":  "0",  "points_1": "5",   "points_2": "77",   "points_3": "89",   "points_4": "217",   "points_5": "521",},
    "words": {"words_0": "0","words_1": "1","words_2": "4","words_3": "5","words_4": "7","words_5": "9",},
    "newPoints":{"nPts_0" :   "0",  "nPts_1" :  "5",   "nPts_2" :  "72",   "nPts_3" :  "12",   "nPts_4" :  "128",   "nPts_5" : "304",},
    "newWords": {"nWords_0": "0","nWords_1": "1","nWords_2": "3","nWords_3": "1","nWords_4": "2","nWords_5": "2",}
  },              
};
/// This list goes through the steps of the tutoial walkthrough
List<Map<String, dynamic>> tutorialDetails = [

  {
    "step" :      0,
    "text" :      "",
    "targets" :   [],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': false,
    'isGameEnded': false,
    'height': 1.0,
    'left': true,
  },

  {
    "step" :      1,
    "text" :      "To skip the tutorial at any step, click on 'Skip Tutorial' at the top",
    "targets" :   ["skip_tutorial"],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.15,
    'left': false,    
  },

  {
    "step" :      2,
    "text" :      "To go back one step, tap the circular arrow icon at the top",
    "targets" :   ["back_step"],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,  
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.15,
    'left': false,
  },      


  {
    "step" :      3,
    "text" :      "The objective is to score as many points as possible by spelling words",
    "targets" :   ["points"],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null, 
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.2,
    'left': false,
  },


  {
    "step" :      4,
    "text" :      "Every turn, you place the upcoming letter",
    "targets" :   ["random_letter_1"],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.45,
    'left': false,   
  },  

  {
    "step" :      5,
    "text" :      "Tap the glowing tile to play the upcoming letter",
    "targets" :   [9],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 9,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.65,
    'left': true,     
  },  
  

  {
    "step" :      6,
    "text" :      "A new letter is randomly generated",
    "targets" :   ['random_letter_2'],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_9',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.40,
    'left': true,     
  },

  {
    "step" :      7,
    "text" :      "You have a limited amount of time to make a move",
    "targets" :   ["countdown"],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null, 
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.4,
    'left': true,     
  },

  {
    "step" :      8,
    "text" :      "If the timer runs out, a random spot on the board will be locked for the rest of the game!",
    "targets" :   [35],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  true,
    "input":      'tile_35',
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.55,
    'left': false,     
  },

  {
    "step" :      9,
    "text" :      "For simplicity, the timer will be disabled for the tutorial",
    "targets" :   [],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.4,  
    'left': true,   
  },     

  {
    "step" :      10,
    "text" :      "Now back to business, tap the glowing tile to place the next letter",
    "targets" :   [8],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 8,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.65,  
    'left': true,    
  },        

  {
    "step" :      11,
    "text" :      "Notice that 1-letter and 2-letter words aren't scored here... ",
    "targets" :   [8,9],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_8',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,  
    'height': 0.65,   
    'left': true,   
  },  

  {
    "step" :      12,
    "text" :      "Only 3-letter words or more will get you points... Tap the glowing tile to complete the word",
    "targets" :   [7],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 7,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.65,  
    'left': true,    
  }, 

  {
    "step" :      13,
    "text" :      "Congratulations! You just played the word “word_1” !",
    "targets" :   [7,8,9, 'new_points', 'new_words'],
    "points":     "points_0",
    "words":      0,
    "newPoints":  "nPts_1",
    "newWords":   1,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_7',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [7,8,9],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.65, 
    'left': false,   
  },   


  {
    "step" :      14,
    "text" :      "Your new score will be tallied ",
    "targets" :   ['points','words'],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [7,8,9],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.2, 
    'left': true,   
  },  


  {
    "step" :      15,
    "text" :      "And the old tiles will be replaced with new ones",
    "targets" :   [7,8,9],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,
    'height': 0.65,  
    'left': true,   
  },


  {
    "step" :      16,
    "text" :      "Now let's find out what these tiles at the bottom do",
    "targets" :   ['reserve_0','reserve_1','reserve_2','reserve_3','reserve_4'],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    

  {
    "step" :      17,
    "text" :      "They serve to help you strategically save letters you want to play later in the game",
    "targets" :   ['reserve_0','reserve_1','reserve_2','reserve_3','reserve_4'],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      18,
    "text" :      "To use them simply tap into one of the empty reserve spots. Tap the glowing reserve spot",
    "targets" :   ['reserve_1',],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 'reserve_1',
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      19,
    "text" :      "You have at most 5 reserves, tap the glowing reserve spot to place the next letter",
    "targets" :   ['reserve_2'],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      "reserve_1",
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 'reserve_2',
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    
  
  {
    "step" :      20,
    "text" :      "You'll see how these letters can be strategically played in a moment",
    "targets" :   [],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      "reserve_2",
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      21,
    "text" :      "Let's start filling up the board with letters",
    "targets" :   [],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 

  //// ------------------ SKIP ---------------------------

  {
    "step" :      22,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [0],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 0,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      23,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [6],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_0',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 6,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      24,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [2],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_6',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 2,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      25,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [20],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_2',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 20,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },       

  {
    "step" :      26,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [22],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_20',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 22,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      27,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [27],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_22',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 27,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },         

  {
    "step" :      28,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [15],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_27',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 15,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  
  
  {
    "step" :      29,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [5],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_15',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 5,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      30,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [24],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_5',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 24,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    

  {
    "step" :      31,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [4],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_24',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 4,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     


  {
    "step" :      32,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [17],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_4',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 17,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      33,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [18],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_17',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 18,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 

  {
    "step" :      34,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [29],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_18',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 29,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },      


  {
    "step" :      35,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [30],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_29',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 30,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },


  /// ------------------------- RESUME ----------------------------------

  {
    "step" :      36,
    "text" :      "Great! Now let's see how we can score some real points!",
    "targets" :   [],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_30',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },        



  {
    "step" :      37,
    "text" :      "Let's play the word “word_4”  by placing the “letter_05” from our reserves into the glowing tile",
    "targets" :   ['reserve_1', 3],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': 'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 3,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },
  
  {
    "step" :      38,
    "text" :      "Good job! You just played three words! “word_4”, “word_2”, and “word_3”",
    "targets" :   [ 2,3,4,5],
    "points":     "points_1",
    "words":      1,
    "newPoints":  "nPts_0",
    "newWords":   3,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_3',
    "inputType":  'drag',
    'isTapped':   false,
    'isDrag':     true, //true,
    'dragSource': 'reserve_1', //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [2,3,4,5],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      39,
    "text" :      "Your score is multiplied by the number of words you found this turn. This brings your score to nPts_2 for this turn!",
    "targets" :   ['new_points','new_words','multi_word', 2,3,4,5],
    "points":     "points_2",
    "words":      4,
    "newPoints":  "nPts_2",
    "newWords":   3,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [2,3,4,5],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      40,
    "text" :      "Your tally climbs to points_2 points and 4 words!",
    "targets" :   ['points','words', 2,3,4,5],
    "points":     "points_2",
    "words":      4,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [2,3,4,5],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },           


  {
    "step" :      41,
    "text" :      "There are other ways you can multiply your score... Tap the glowing tile to create the word “word_5”",
    "targets" :   [23],
    "points":     "points_2",
    "words":      4,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 23,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },      

  {
    "step" :      42,
    "text" :      "You just scored for a second turn in a row! You're on a hot streak!",
    "targets" :   [17,23,29, 'new_points', 'new_words','streak'],
    "points":     "points_2",
    "words":      4,
    "newPoints":  "nPts_3",
    "newWords":   1,
    "streak":     2,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_23',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [17,23,29],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      43,
    "text" :      "Your points are tallied and the streak persists",
    "targets" :   ['streak','points', 'words'],
    "points":     "points_3",
    "words":      5,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     2,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [17,23,29],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },


  {
    "step" :      44,
    "text" :      "You can also double your score by finding words and the horizonal and vertical axis",
    "targets" :   [],
    "points":     "points_3",
    "words":      5,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      45,
    "text" :      "Drag the glowing reserve tile into the glowing tile on the board to create a crossword",
    "targets" :   ['reserve_2',21],
    "points":     "points_3",
    "words":      5,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': 'reserve_2', //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 21,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      46,
    "text" :      "You just crossed the word “word_7” with “word_6”!",
    "targets" :   [ 15, 20, 21, 22, 27],
    "points":     "points_3",
    "words":      5,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     3,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_21',
    "inputType":  'drag',
    'isTapped':   false,
    'isDrag':     true, //true,
    'dragSource': 'reserve_2', //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [15, 20, 21, 22, 27],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      47,
    "text" :      "You just multiplied your initial points by 12!!! (3 * 2 * 2)",
    "targets" :   ['new_points', 'new_words', 'streak', 'multi_word', 'cross_word',  15, 20, 21, 22, 27],
    "points":     "points_3",
    "words":      5,
    "newPoints":  "nPts_4",
    "newWords":   2,
    "streak":     3,
    "crossword":  2,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [15, 20, 21, 22, 27],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      48,
    "text" :      "Next we'll see what happens when we find words that are 5 and 6 letters long",
    "targets" :   [],
    "points":     "points_4",
    "words":      7,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [15, 20, 21, 22, 27],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    

  

  {
    "step" :      49,
    "text" :      "5 letter words and 6 letter words are doubled and tripled in value respectively...",
    "targets" :   [],
    "points":     "points_4",
    "words":      7,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },       

  {
    "step" :      50,
    "text" :      "Tap the glowing tile to place the letter “letter_22”",
    "targets" :   [12],
    "points":     "points_4",
    "words":      7,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 12,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      51,
    "text" :      "You just found the words “word_8” and “word_9”",
    "targets" :   [0, 6, 12, 18, 24, 30],
    "points":     "points_4",
    "words":      7,
    "newPoints":  "nPts_5",
    "newWords":   2,
    "streak":     4,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_12',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [0, 6, 12, 18, 24, 30],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      52,
    "text" :      "With the word multiplier (2x) and streak multiplier (4x) you're at nPts_5 points!",
    "targets" :   [0, 6, 12, 18, 24, 30, 'multi_word', 'streak', 'new_points','new_words'],
    "points":     "points_4",
    "words":      7,
    "newPoints":  "nPts_5",
    "newWords":   2,
    "streak":     4,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [0, 6, 12, 18, 24, 30],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      53,
    "text" :      "Now your score will be tallied and reflect the new tally of points_5 points!",
    "targets" :   ['words', 'points'],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [0, 6, 12, 18, 24, 30],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },


  {
    "step" :      54,
    "text" :      "That's pretty much it! Last thing to show you is the pause menu. Click the glowing pause button.",
    "targets" :   ['pause'],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'pause',
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      55,
    "text" :      "The pause menu displays the game summary as well as a summary of scored points! tap 'View score summary' to see it",
    "targets" :   ["view_score_summary"],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'view_score_summary',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 


  {
    "step" :      56,
    "text" :      "All the words are tabulated with their multipliers!",
    "targets" :   [],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      57,
    "text" :      "You can navigate to the instructions page for a refresher on how to play - Tap the glowing help icon",
    "targets" :   ["help_icon"],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'help_icon',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      58,
    "text" :      "You can adjust parameters on the settings page - Tap the glowing settings icon",
    "targets" :   ["settings_icon"],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'settings_icon',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      59,
    "text" :      "And finally, you can exit the game or restart at any time - Tap the exit icon",
    "targets" :   ["exit_icon"],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'exit_icon',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },                      


  {
    "step" :      60,
    "text" :      "",
    "targets" :   [],
    "points":     "points_5",
    "words":      9,
    "newPoints":  "nPts_0",
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': true,         
  },

];

