// import 'package:scribby_flutter_v2/functions/game_logic.dart';

List<Map<String, dynamic>> initialBoardState = [
  // ROW 1
  {"tileId": "1_1","row": 1,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "1_2","row": 1,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "1_3","row": 1,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "1_4","row": 1,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "1_5","row": 1,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "1_6","row": 1,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 2
  {"tileId": "2_1","row": 2,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "2_2","row": 2,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "2_3","row": 2,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "2_4","row": 2,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "2_5","row": 2,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "2_6","row": 2,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 3
  {"tileId": "3_1","row": 3,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "3_2","row": 3,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "3_3","row": 3,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "3_4","row": 3,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "3_5","row": 3,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "3_6","row": 3,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 4
  {"tileId": "4_1","row": 4,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "4_2","row": 4,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "4_3","row": 4,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "4_4","row": 4,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "4_5","row": 4,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "4_6","row": 4,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 5
  {"tileId": "5_1","row": 5,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "5_2","row": 5,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "5_3","row": 5,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "5_4","row": 5,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "5_5","row": 5,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "5_6","row": 5,"column": 6,"letter": "","active": false,"alive": true},
  // ROW 6
  {"tileId": "6_1","row": 6,"column": 1,"letter": "","active": false,"alive": true},
  {"tileId": "6_2","row": 6,"column": 2,"letter": "","active": false,"alive": true},
  {"tileId": "6_3","row": 6,"column": 3,"letter": "","active": false,"alive": true},
  {"tileId": "6_4","row": 6,"column": 4,"letter": "","active": false,"alive": true},
  {"tileId": "6_5","row": 6,"column": 5,"letter": "","active": false,"alive": true},
  {"tileId": "6_6","row": 6,"column": 6,"letter": "","active": false,"alive": true},
];

List<Map<String, dynamic>> alphabets = [
  {
    "language": "english",
    "alphabet": englishAlphabet,
  },
  {
    "language": "french",
    "alphabet": frenchAlphabet,
  },
];

// List<Map<String,dynamic>> initialRandomLetterState = [
//   {"letter" : "A", "type" : "vowel",      "points": 1,  "count": 86, "inPlay": 0},
//   {"letter" : "B", "type" : "consonant",  "points": 3,  "count": 24, "inPlay": 0},
//   {"letter" : "C", "type" : "consonant",  "points": 1,  "count": 33, "inPlay": 0},
//   {"letter" : "D", "type" : "consonant",  "points": 2,  "count": 39, "inPlay": 0},
//   {"letter" : "E", "type" : "vowel",      "points": 1,  "count": 111, "inPlay": 0},
//   {"letter" : "F", "type" : "consonant",  "points": 3,  "count": 17, "inPlay": 0},
//   {"letter" : "G", "type" : "consonant",  "points": 1,  "count": 27, "inPlay": 0},
//   {"letter" : "H", "type" : "consonant",  "points": 1,  "count": 27, "inPlay": 0},
//   {"letter" : "I", "type" : "vowel",      "points": 1,  "count": 64, "inPlay": 0},
//   {"letter" : "J", "type" : "consonant",  "points": 10, "count": 4, "inPlay": 0},
//   {"letter" : "K", "type" : "consonant",  "points": 1,  "count": 21, "inPlay": 0},
//   {"letter" : "L", "type" : "consonant",  "points": 2,  "count": 54, "inPlay": 0},
//   {"letter" : "M", "type" : "consonant",  "points": 1,  "count": 30, "inPlay": 0},
//   {"letter" : "N", "type" : "consonant",  "points": 2,  "count": 49, "inPlay": 0},
//   {"letter" : "O", "type" : "vowel",      "points": 1,  "count": 64, "inPlay": 0},
//   {"letter" : "P", "type" : "consonant",  "points": 1,  "count": 29, "inPlay": 0},
//   {"letter" : "Q", "type" : "consonant",  "points": 10, "count": 2, "inPlay": 0},
//   {"letter" : "R", "type" : "consonant",  "points": 1,  "count": 67, "inPlay": 0},
//   {"letter" : "S", "type" : "consonant",  "points": 1,  "count": 95, "inPlay": 0},
//   {"letter" : "T", "type" : "consonant",  "points": 2,  "count": 50, "inPlay": 0},
//   {"letter" : "U", "type" : "vowel",      "points": 2,  "count": 21, "inPlay": 0}, // count originally 41
//   {"letter" : "V", "type" : "consonant",  "points": 2,  "count": 11, "inPlay": 0},
//   {"letter" : "W", "type" : "consonant",  "points": 2,  "count": 15, "inPlay": 0},
//   {"letter" : "X", "type" : "consonant",  "points": 5,  "count": 4, "inPlay": 0},
//   {"letter" : "Y", "type" : "consonant",  "points": 5,  "count": 27, "inPlay": 0},
//   {"letter" : "Z", "type" : "consonant",  "points": 9,  "count": 7, "inPlay": 0},
// ];

// List<Map<String,dynamic>> initialRandomLetterState = getInitialRandomLetterState()

// List<Map<String,dynamic>> startingAlphabetState = GameLogic().generateStartingStates(initialRandomLetterState, initialBoardState, [])['startingAlphabet'];
// List<String> randomLetterListState = GameLogic().generateStartingStates(initialRandomLetterState, initialBoardState, [])['startingRandomLetterList'];
// List<Map<String,dynamic>> startingTileState = GameLogic().generateStartingStates(initialRandomLetterState, initialBoardState, [])['startingTileState'];
// List<String> randomLetterListState = [];

List<Map<String, dynamic>> turnSummaryState = [];

List<Map<String, dynamic>> stringCombinations = [
  {'len': 3,'arr': ['1_1', '1_2', '1_3'],'axis': 'row'  },
  {'len': 3,'arr': ['1_2', '1_3', '1_4'],'axis': 'row'  },
  {'len': 3,'arr': ['1_3', '1_4', '1_5'],'axis': 'row'  },
  {'len': 3,'arr': ['1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 3,'arr': ['2_1', '2_2', '2_3'],'axis': 'row'  },
  {'len': 3,'arr': ['2_2', '2_3', '2_4'],'axis': 'row'  },
  {'len': 3,'arr': ['2_3', '2_4', '2_5'],'axis': 'row'  },
  {'len': 3,'arr': ['2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 3,'arr': ['3_1', '3_2', '3_3'],'axis': 'row'  },
  {'len': 3,'arr': ['3_2', '3_3', '3_4'],'axis': 'row'  },
  {'len': 3,'arr': ['3_3', '3_4', '3_5'],'axis': 'row'  },
  {'len': 3,'arr': ['3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 3,'arr': ['4_1', '4_2', '4_3'],'axis': 'row'  },
  {'len': 3,'arr': ['4_2', '4_3', '4_4'],'axis': 'row'  },
  {'len': 3,'arr': ['4_3', '4_4', '4_5'],'axis': 'row'  },
  {'len': 3,'arr': ['4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 3,'arr': ['5_1', '5_2', '5_3'],'axis': 'row'  },
  {'len': 3,'arr': ['5_2', '5_3', '5_4'],'axis': 'row'  },
  {'len': 3,'arr': ['5_3', '5_4', '5_5'],'axis': 'row'  },
  {'len': 3,'arr': ['5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 3,'arr': ['6_1', '6_2', '6_3'],'axis': 'row'  },
  {'len': 3,'arr': ['6_2', '6_3', '6_4'],'axis': 'row'  },
  {'len': 3,'arr': ['6_3', '6_4', '6_5'],'axis': 'row'  },
  {'len': 3,'arr': ['6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 4,'arr': ['1_1', '1_2', '1_3', '1_4'],'axis': 'row'  },
  {'len': 4,'arr': ['1_2', '1_3', '1_4', '1_5'],'axis': 'row'  },
  {'len': 4,'arr': ['1_3', '1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 4,'arr': ['2_1', '2_2', '2_3', '2_4'],'axis': 'row'  },
  {'len': 4,'arr': ['2_2', '2_3', '2_4', '2_5'],'axis': 'row'  },
  {'len': 4,'arr': ['2_3', '2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 4,'arr': ['3_1', '3_2', '3_3', '3_4'],'axis': 'row'  },
  {'len': 4,'arr': ['3_2', '3_3', '3_4', '3_5'],'axis': 'row'  },
  {'len': 4,'arr': ['3_3', '3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 4,'arr': ['4_1', '4_2', '4_3', '4_4'],'axis': 'row'  },
  {'len': 4,'arr': ['4_2', '4_3', '4_4', '4_5'],'axis': 'row'  },
  {'len': 4,'arr': ['4_3', '4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 4,'arr': ['5_1', '5_2', '5_3', '5_4'],'axis': 'row'  },
  {'len': 4,'arr': ['5_2', '5_3', '5_4', '5_5'],'axis': 'row'  },
  {'len': 4,'arr': ['5_3', '5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 4,'arr': ['6_1', '6_2', '6_3', '6_4'],'axis': 'row'  },
  {'len': 4,'arr': ['6_2', '6_3', '6_4', '6_5'],'axis': 'row'  },
  {'len': 4,'arr': ['6_3', '6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 5,'arr': ['1_1', '1_2', '1_3', '1_4', '1_5'],'axis': 'row'  },
  {'len': 5,'arr': ['1_2', '1_3', '1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 5,'arr': ['2_1', '2_2', '2_3', '2_4', '2_5'],'axis': 'row'  },
  {'len': 5,'arr': ['2_2', '2_3', '2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 5,'arr': ['3_1', '3_2', '3_3', '3_4', '3_5'],'axis': 'row'  },
  {'len': 5,'arr': ['3_2', '3_3', '3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 5,'arr': ['4_1', '4_2', '4_3', '4_4', '4_5'],'axis': 'row'  },
  {'len': 5,'arr': ['4_2', '4_3', '4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 5,'arr': ['5_1', '5_2', '5_3', '5_4', '5_5'],'axis': 'row'  },
  {'len': 5,'arr': ['5_2', '5_3', '5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 5,'arr': ['6_1', '6_2', '6_3', '6_4', '6_5'],'axis': 'row'  },
  {'len': 5,'arr': ['6_2', '6_3', '6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 6,'arr': ['1_1', '1_2', '1_3', '1_4', '1_5', '1_6'],'axis': 'row'  },
  {'len': 6,'arr': ['2_1', '2_2', '2_3', '2_4', '2_5', '2_6'],'axis': 'row'  },
  {'len': 6,'arr': ['3_1', '3_2', '3_3', '3_4', '3_5', '3_6'],'axis': 'row'  },
  {'len': 6,'arr': ['4_1', '4_2', '4_3', '4_4', '4_5', '4_6'],'axis': 'row'  },
  {'len': 6,'arr': ['5_1', '5_2', '5_3', '5_4', '5_5', '5_6'],'axis': 'row'  },
  {'len': 6,'arr': ['6_1', '6_2', '6_3', '6_4', '6_5', '6_6'],'axis': 'row'  },
  {'len': 3,'arr': ['1_1', '2_1', '3_1'],'axis': 'column'  },
  {'len': 3,'arr': ['1_2', '2_2', '3_2'],'axis': 'column'  },
  {'len': 3,'arr': ['1_3', '2_3', '3_3'],'axis': 'column'  },
  {'len': 3,'arr': ['1_4', '2_4', '3_4'],'axis': 'column'  },
  {'len': 3,'arr': ['1_5', '2_5', '3_5'],'axis': 'column'  },
  {'len': 3,'arr': ['1_6', '2_6', '3_6'],'axis': 'column'  },
  {'len': 3,'arr': ['2_1', '3_1', '4_1'],'axis': 'column'  },
  {'len': 3,'arr': ['2_2', '3_2', '4_2'],'axis': 'column'  },
  {'len': 3,'arr': ['2_3', '3_3', '4_3'],'axis': 'column'  },
  {'len': 3,'arr': ['2_4', '3_4', '4_4'],'axis': 'column'  },
  {'len': 3,'arr': ['2_5', '3_5', '4_5'],'axis': 'column'  },
  {'len': 3,'arr': ['2_6', '3_6', '4_6'],'axis': 'column'  },
  {'len': 3,'arr': ['3_1', '4_1', '5_1'],'axis': 'column'  },
  {'len': 3,'arr': ['3_2', '4_2', '5_2'],'axis': 'column'  },
  {'len': 3,'arr': ['3_3', '4_3', '5_3'],'axis': 'column'  },
  {'len': 3,'arr': ['3_4', '4_4', '5_4'],'axis': 'column'  },
  {'len': 3,'arr': ['3_5', '4_5', '5_5'],'axis': 'column'  },
  {'len': 3,'arr': ['3_6', '4_6', '5_6'],'axis': 'column'  },
  {'len': 3,'arr': ['4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 3,'arr': ['4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 3,'arr': ['4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 3,'arr': ['4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 3,'arr': ['4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 3,'arr': ['4_6', '5_6', '6_6'],'axis': 'column'  },
  {'len': 4,'arr': ['1_1', '2_1', '3_1', '4_1'],'axis': 'column'  },
  {'len': 4,'arr': ['1_2', '2_2', '3_2', '4_2'],'axis': 'column'  },
  {'len': 4,'arr': ['1_3', '2_3', '3_3', '4_3'],'axis': 'column'  },
  {'len': 4,'arr': ['1_4', '2_4', '3_4', '4_4'],'axis': 'column'  },
  {'len': 4,'arr': ['1_5', '2_5', '3_5', '4_5'],'axis': 'column'  },
  {'len': 4,'arr': ['1_6', '2_6', '3_6', '4_6'],'axis': 'column'  },
  {'len': 4,'arr': ['2_1', '3_1', '4_1', '5_1'],'axis': 'column'  },
  {'len': 4,'arr': ['2_2', '3_2', '4_2', '5_2'],'axis': 'column'  },
  {'len': 4,'arr': ['2_3', '3_3', '4_3', '5_3'],'axis': 'column'  },
  {'len': 4,'arr': ['2_4', '3_4', '4_4', '5_4'],'axis': 'column'  },
  {'len': 4,'arr': ['2_5', '3_5', '4_5', '5_5'],'axis': 'column'  },
  {'len': 4,'arr': ['2_6', '3_6', '4_6', '5_6'],'axis': 'column'  },
  {'len': 4,'arr': ['3_1', '4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 4,'arr': ['3_2', '4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 4,'arr': ['3_3', '4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 4,'arr': ['3_4', '4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 4,'arr': ['3_5', '4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 4,'arr': ['3_6', '4_6', '5_6', '6_6'],'axis': 'column'  },
  {'len': 5,'arr': ['1_1', '2_1', '3_1', '4_1', '5_1'],'axis': 'column'  },
  {'len': 5,'arr': ['1_2', '2_2', '3_2', '4_2', '5_2'],'axis': 'column'  },
  {'len': 5,'arr': ['1_3', '2_3', '3_3', '4_3', '5_3'],'axis': 'column'  },
  {'len': 5,'arr': ['1_4', '2_4', '3_4', '4_4', '5_4'],'axis': 'column'  },
  {'len': 5,'arr': ['1_5', '2_5', '3_5', '4_5', '5_5'],'axis': 'column'  },
  {'len': 5,'arr': ['1_6', '2_6', '3_6', '4_6', '5_6'],'axis': 'column'  },
  {'len': 5,'arr': ['2_1', '3_1', '4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 5,'arr': ['2_2', '3_2', '4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 5,'arr': ['2_3', '3_3', '4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 5,'arr': ['2_4', '3_4', '4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 5,'arr': ['2_5', '3_5', '4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 5,'arr': ['2_6', '3_6', '4_6', '5_6', '6_6'],'axis': 'column'  },
  {'len': 6,'arr': ['1_1', '2_1', '3_1', '4_1', '5_1', '6_1'],'axis': 'column'  },
  {'len': 6,'arr': ['1_2', '2_2', '3_2', '4_2', '5_2', '6_2'],'axis': 'column'  },
  {'len': 6,'arr': ['1_3', '2_3', '3_3', '4_3', '5_3', '6_3'],'axis': 'column'  },
  {'len': 6,'arr': ['1_4', '2_4', '3_4', '4_4', '5_4', '6_4'],'axis': 'column'  },
  {'len': 6,'arr': ['1_5', '2_5', '3_5', '4_5', '5_5', '6_5'],'axis': 'column'  },
  {'len': 6,'arr': ['1_6', '2_6', '3_6', '4_6', '5_6', '6_6'],'axis': 'column'  },
];

List<Map<String, dynamic>> demoBoardState_1 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "A", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "K", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_2 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "K", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "U", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "A", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_3 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "U", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "S", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "A", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "K", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_4 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "S", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "E", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "A", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "K", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "U", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_5 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "E", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "N", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "A", "active": true},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "S", "active": true},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "K", "active": true},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "U", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> demoBoardState_6 = [
  // Random Letters
  {"tileId": "0_0", "row": 0, "column": 0, "letter": "E", "active": false},
  {"tileId": "0_1", "row": 0, "column": 1, "letter": "N", "active": false},
  // Board
  {"tileId": "1_1", "row": 1, "column": 1, "letter": "", "active": false},
  {"tileId": "1_2", "row": 1, "column": 2, "letter": "", "active": false},
  {"tileId": "1_3", "row": 1, "column": 3, "letter": "", "active": false},
  {"tileId": "2_1", "row": 2, "column": 1, "letter": "", "active": false},
  {"tileId": "2_2", "row": 2, "column": 2, "letter": "", "active": false},
  {"tileId": "2_3", "row": 2, "column": 3, "letter": "U", "active": false},
  {"tileId": "3_1", "row": 3, "column": 1, "letter": "", "active": false},
  {"tileId": "3_2", "row": 3, "column": 2, "letter": "", "active": false},
  {"tileId": "3_3", "row": 3, "column": 3, "letter": "", "active": false},
];

List<Map<String, dynamic>> englishAlphabet = [
  {"letter": "A", "type": "vowel", "points": 1, "count": 86, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 24, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 1, "count": 33, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 39, "inPlay": 0},
  {"letter": "E", "type": "vowel", "points": 1, "count": 111, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 3, "count": 17, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 1, "count": 27, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 1, "count": 27, "inPlay": 0},
  {"letter": "I", "type": "vowel", "points": 1, "count": 64, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 10, "count": 4, "inPlay": 0},
  {"letter": "K", "type": "consonant", "points": 1, "count": 21, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 2, "count": 54, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 1, "count": 30, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 2, "count": 49, "inPlay": 0},
  {"letter": "O", "type": "vowel", "points": 1, "count": 64, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 1, "count": 29, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 10, "count": 2, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 67, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 95, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 2, "count": 50, "inPlay": 0},
  {"letter": "U", "type": "vowel",      "points": 2,"count": 21,  "inPlay": 0}, // count originally 41
  {"letter": "V", "type": "consonant", "points": 2, "count": 11, "inPlay": 0},
  {"letter": "W", "type": "consonant", "points": 2, "count": 15, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 5, "count": 4, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 5, "count": 27, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 9, "count": 7, "inPlay": 0},
];

List<Map<String, dynamic>> frenchAlphabet = [
  {"letter": "A", "type": "vowel", "points": 1, "count": 90, "inPlay": 0},
  {"letter": "B", "type": "consonant", "points": 3, "count": 20, "inPlay": 0},
  {"letter": "C", "type": "consonant", "points": 1, "count": 20, "inPlay": 0},
  {"letter": "D", "type": "consonant", "points": 2, "count": 30, "inPlay": 0},
  {"letter": "E", "type": "vowel", "points": 1, "count": 150, "inPlay": 0},
  {"letter": "F", "type": "consonant", "points": 4, "count": 20, "inPlay": 0},
  {"letter": "G", "type": "consonant", "points": 2, "count": 20, "inPlay": 0},
  {"letter": "H", "type": "consonant", "points": 4, "count": 20, "inPlay": 0},
  {"letter": "I", "type": "vowel", "points": 1, "count": 80, "inPlay": 0},
  {"letter": "J", "type": "consonant", "points": 8, "count": 10, "inPlay": 0},
  {"letter": "K", "type": "consonant", "points": 10, "count": 10, "inPlay": 0},
  {"letter": "L", "type": "consonant", "points": 1, "count": 50, "inPlay": 0},
  {"letter": "M", "type": "consonant", "points": 2, "count": 30, "inPlay": 0},
  {"letter": "N", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "O", "type": "vowel", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "P", "type": "consonant", "points": 3, "count": 20, "inPlay": 0},
  {"letter": "Q", "type": "consonant", "points": 8, "count": 3, "inPlay": 0},
  {"letter": "R", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "S", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {"letter": "T", "type": "consonant", "points": 1, "count": 60, "inPlay": 0},
  {
    "letter": "U",
    "type": "vowel",
    "points": 1,
    "count": 60,
    "inPlay": 0
  }, // count originally 41
  {"letter": "V", "type": "consonant", "points": 4, "count": 20, "inPlay": 0},
  {"letter": "W", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
  {"letter": "X", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
  {"letter": "Y", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
  {"letter": "Z", "type": "consonant", "points": 10, "count": 3, "inPlay": 0},
];

List<Map<String, dynamic>> tutorialBoard_1 = [
  // // Random Letters
  // {"tileId" : "0_0", "row":0 , "column":0 , "letter" : "E", "active": false},
  // {"tileId" : "0_1", "row":0 , "column":1 , "letter" : "N", "active": false},
  // Board
  {"index": 0,"tileId": "1_1","row": 1,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 1,"tileId": "1_2","row": 1,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 2,"tileId": "1_3","row": 1,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 3,"tileId": "1_4","row": 1,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 4,"tileId": "1_5","row": 1,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 5,"tileId": "1_6","row": 1,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 6,"tileId": "2_1","row": 2,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 7,"tileId": "2_2","row": 2,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 8,"tileId": "2_3","row": 2,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 9,"tileId": "2_4","row": 2,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 10,"tileId": "2_5","row": 2,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 11,"tileId": "2_6","row": 2,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 12,"tileId": "3_1","row": 3,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 13,"tileId": "3_2","row": 3,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 14,"tileId": "3_3","row": 3,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 15,"tileId": "3_4","row": 3,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 16,"tileId": "3_5","row": 3,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 17,"tileId": "3_6","row": 3,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 18,"tileId": "4_1","row": 4,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 19,"tileId": "4_2","row": 4,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 20,"tileId": "4_3","row": 4,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 21,"tileId": "4_4","row": 4,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 22,"tileId": "4_5","row": 4,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 23,"tileId": "4_6","row": 4,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 24,"tileId": "5_1","row": 5,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 25,"tileId": "5_2","row": 5,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 26,"tileId": "5_3","row": 5,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 27,"tileId": "5_4","row": 5,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 28,"tileId": "5_5","row": 5,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 29,"tileId": "5_6","row": 5,"column": 6,"letter": "","active": false, "alive": true  },

  {"index": 30,"tileId": "6_1","row": 6,"column": 1,"letter": "","active": false, "alive": true  },
  {"index": 31,"tileId": "6_2","row": 6,"column": 2,"letter": "","active": false, "alive": true  },
  {"index": 32,"tileId": "6_3","row": 6,"column": 3,"letter": "","active": false, "alive": true  },
  {"index": 33,"tileId": "6_4","row": 6,"column": 4,"letter": "","active": false, "alive": true  },
  {"index": 34,"tileId": "6_5","row": 6,"column": 5,"letter": "","active": false, "alive": true  },
  {"index": 35,"tileId": "6_6","row": 6,"column": 6,"letter": "","active": false, "alive": true  },
];

/// This list goes through the steps of the tutoial walkthrough
List<Map<String, dynamic>> tutorialDetails = [
  // {"step": 0,"text":"Welcome to Scribby! This tutorial will show you how to play the game", "targets": []},
  // {"step": 1,"text": "To skip the tutorial at any step, click on 'Skip Tutorial' at the top", "targets": ['skip_tutorial']},
  // {"step": 2, "text": "To go back one step, tap the circular arrow icon at the top", "targets": ['back_step']},


  {
    "step" :      0,
    "text" :      "Welcome to Scribby! This tutorial will show you how to play the game",
    "targets" :   [],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': false,
    'isGameEnded': false,
  },

  {
    "step" :      1,
    "text" :      "To skip the tutorial at any step, click on 'Skip Tutorial' at the top",
    "targets" :   ["skip_tutorial"],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': false,
    'isGameEnded': false,    
  },

  {
    "step" :      2,
    "text" :      "To go back one step, tap the circular arrow icon at the top",
    "targets" :   ["back_step"],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,  
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': false,
    'isGameEnded': false,    
  },      


  {
    "step" :      3,
    "text" :      "The objective is to score as many points as possible by spelling words",
    "targets" :   ["points"],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null, 
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,    
  },


  {
    "step" :      4,
    "text" :      "Every turn, you place the upcoming letter",
    "targets" :   ["random_letter_1"],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      5,
    "text" :      "Tap the glowing tile to play the upcoming letter",
    "targets" :   [9],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 9,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  
  

  {
    "step" :      6,
    "text" :      "A new letter is randomly generated",
    "targets" :   ['random_letter_2'],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_9',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      7,
    "text" :      "You have a limited amount of time to make a move",
    "targets" :   ["countdown"],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null, 
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      8,
    "text" :      "If the timer runs out, a random spot on the board will be locked for the rest of the game!",
    "targets" :   [35],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  true,
    "input":      'tile_35',
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      9,
    "text" :      "For simplicity, the timer will be disabled for the tutorial",
    "targets" :   [],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      10,
    "text" :      "Now back to business, tap the glowing tile to place the next letter",
    "targets" :   [8],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 8,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },        

  {
    "step" :      11,
    "text" :      "Notice that 1-letter and 2-letter words aren't scored here... ",
    "targets" :   [8,9],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_8',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      12,
    "text" :      "Only 3-letter words or more will get you points... Tap the glowing tile to complete the word",
    "targets" :   [7],
    "points":     0,
    "words":      0,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 7,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 

  {
    "step" :      13,
    "text" :      "Huzzah! You just played the word 'CAT'! ",
    "targets" :   [7,8,9, 'new_points', 'new_words'],
    "points":     0,
    "words":      0,
    "newPoints":  4,
    "newWords":   1,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_7',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [7,8,9],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   


  {
    "step" :      14,
    "text" :      "Your new score will be tallied ",
    "targets" :   ['points','words'],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [7,8,9],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      15,
    "text" :      "And the old tiles will be replaced with new ones",
    "targets" :   [7,8,9],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },


  {
    "step" :      16,
    "text" :      "Now let's find out what these tiles at the bottom do",
    "targets" :   ['reserve_0','reserve_1','reserve_2','reserve_3','reserve_4'],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    

  {
    "step" :      17,
    "text" :      "They serve to help you strategically save letters you want to play later in the game",
    "targets" :   ['reserve_0','reserve_1','reserve_2','reserve_3','reserve_4'],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      18,
    "text" :      "To use them simply tap into one of the empty reserve spots. Tap the glowing reserve spot",
    "targets" :   ['reserve_1',],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 'reserve_1',
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      19,
    "text" :      "You have at most 5 reserves, tap the glowing reserve spot to place the next letter",
    "targets" :   ['reserve_2'],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      "reserve_1",
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 'reserve_2',
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    
  
  {
    "step" :      20,
    "text" :      "You'll see how these letters can be strategically played in a moment",
    "targets" :   [],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      "reserve_2",
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      21,
    "text" :      "Let's start filling up the board with letters",
    "targets" :   [],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 

  {
    "step" :      22,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [0],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 0,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      23,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [6],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_0',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 6,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      24,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [2],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_6',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 2,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      25,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [20],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_2',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 20,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },       

  {
    "step" :      26,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [22],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_20',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 22,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      27,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [27],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_22',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 27,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },         

  {
    "step" :      28,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [15],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_27',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 15,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  
  
  {
    "step" :      29,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [5],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_15',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 5,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     

  {
    "step" :      30,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [24],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_5',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 24,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    

  {
    "step" :      31,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [4],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_24',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 4,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },     


  {
    "step" :      32,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [17],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_4',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 17,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      33,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [18],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_17',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 18,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 

  {
    "step" :      34,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [29],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_18',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 29,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },      


  {
    "step" :      35,
    "text" :      "Tap the glowing tile to place the upcoming letter",
    "targets" :   [30],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      'tile_29',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': 30,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      36,
    "text" :      "Okay good job! Now let's see how we can score some real points!",
    "targets" :   [],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_30',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },        




  {
    "step" :      37,
    "text" :      "Okay let's get serious!",
    "targets" :   [],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': null,
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },      

  {
    "step" :      38,
    "text" :      "Let's play the word WASP by placing the A from our reserves into the glowing tile",
    "targets" :   ['reserve_1', 3],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false,
    'dragSource': 'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 3,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },
  
  {
    "step" :      39,
    "text" :      "WOW! You just played three words! WASP, WAS, and ASP",
    "targets" :   [ 2,3,4,5],
    "points":     4,
    "words":      1,
    "newPoints":  0,
    "newWords":   3,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_3',
    "inputType":  'drag',
    'isTapped':   false,
    'isDrag':     true, //true,
    'dragSource': 'reserve_1', //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [2,3,4,5],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      40,
    "text" :      "Your score is multipled by the number of words you found this turn. This brings your score from 12 to 36!",
    "targets" :   ['new_points','new_words','multi_word', 2,3,4,5],
    "points":     40,
    "words":      4,
    "newPoints":  36,
    "newWords":   3,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [2,3,4,5],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      41,
    "text" :      "Your tally climbs to 40 points and 4 words!",
    "targets" :   ['points','words', 2,3,4,5],
    "points":     40,
    "words":      4,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [2,3,4,5],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },           


  {
    "step" :      42,
    "text" :      "There are other ways you can multiply your score... Tap the glowing tile to create the word 'HUN'",
    "targets" :   [23],
    "points":     40,
    "words":      4,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 23,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },      

  {
    "step" :      43,
    "text" :      "You just scored for a second turn in a row! You're on a hot streak!",
    "targets" :   [17,23,29, 'new_points', 'new_words','streak'],
    "points":     40,
    "words":      4,
    "newPoints":  10,
    "newWords":   1,
    "streak":     2,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_23',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [17,23,29],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      44,
    "text" :      "Your points are tallied and the streak persists",
    "targets" :   ['streak','points', 'words'],
    "points":     50,
    "words":      5,
    "newPoints":  0,
    "newWords":   0,
    "streak":     2,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [17,23,29],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },


  {
    "step" :      45,
    "text" :      "You can also double your score by finding words and the horizonal and vertical axis",
    "targets" :   [],
    "points":     50,
    "words":      5,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      46,
    "text" :      "Drag the glowing reserve tile into the glowing tile on the board to create a crossword",
    "targets" :   ['reserve_2',21],
    "points":     50,
    "words":      5,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': 'reserve_2', //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 21,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      46,
    "text" :      "You just crossed the word BEG with TEA!",
    "targets" :   [ 15, 20, 21, 22, 27],
    "points":     50,
    "words":      5,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_21',
    "inputType":  'drag',
    'isTapped':   false,
    'isDrag':     true, //true,
    'dragSource': 'reserve_2', //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [15, 20, 21, 22, 27],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      47,
    "text" :      "You just multiplied your initial points of 9 by (3 * 2 * 2)!",
    "targets" :   ['new_points', 'new_words', 'streak', 'multi_word', 'cross_word',  15, 20, 21, 22, 27],
    "points":     50,
    "words":      5,
    "newPoints":  108,
    "newWords":   2,
    "streak":     3,
    "crossword":  2,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [15, 20, 21, 22, 27],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      48,
    "text" :      "Next we'll see what happens when we find words that are 5 and 6 letters long.",
    "targets" :   [],
    "points":     158,
    "words":      7,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [15, 20, 21, 22, 27],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },    

  // {
  //   "step" :      49,
  //   "text" :      "Tap the glowing tile to get rid of the letter",
  //   "targets" :   [5],
  //   "points":     158,
  //   "words":      7,
  //   "newPoints":  0,
  //   "newWords":   0,
  //   "streak":     0,
  //   "crossword":  0,
  //   "complete":   false,
  //   "autoPlace":  false,
  //   "input":      null,
  //   "inputType":  null,
  //   'isTapped':   false,
  //   'isDrag':     false, //true,
  //   'dragSource': null, //'reserve_1',
  //   'tilesToRemove': [],
  //   'callbackTarget': 5,
  //   'tilesInWord':  [],
  //'isPaused':   false,
    //   'isGameStarted': true,
    // 'isGameEnded': false, //   
  // },      

  {
    "step" :      49,
    "text" :      "5 letter words and 6 letter words are doubled and tripled in value respectively...",
    "targets" :   [],
    "points":     158,
    "words":      7,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },       

  {
    "step" :      50,
    "text" :      "Tap the glowing tile to complete the words",
    "targets" :   [12],
    "points":     158,
    "words":      7,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 12,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      51,
    "text" :      "You just found the words PRINT and SPRINT",
    "targets" :   [0, 6, 12, 18, 24, 30],
    "points":     158,
    "words":      7,
    "newPoints":  76,
    "newWords":   2,
    "streak":     4,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      'tile_12',
    "inputType":  'tap',
    'isTapped':   true,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [0, 6, 12, 18, 24, 30],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  

  {
    "step" :      52,
    "text" :      "With the word multiplier (2x) and streak multiplier (4x) you're at 304 points!",
    "targets" :   [0, 6, 12, 18, 24, 30, 'multi_word', 'streak', 'new_points','new_words'],
    "points":     158,
    "words":      7,
    "newPoints":  304,
    "newWords":   2,
    "streak":     4,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [0, 6, 12, 18, 24, 30],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },

  {
    "step" :      53,
    "text" :      "Now your score will be tallied and reflect the new tally of 462!",
    "targets" :   ['words', 'points'],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [0, 6, 12, 18, 24, 30],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },


  {
    "step" :      54,
    "text" :      "That's pretty much it! Last thing to show you is the pause menu. Click the glowing pause button.",
    "targets" :   ['pause'],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'pause',
    'tilesInWord':  [],
    'isPaused':   false,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      55,
    "text" :      "The pause menu displays the game summary as well as a summary of scored points! tap 'View score summary' to see it",
    "targets" :   ["view_score_summary"],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   false,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'view_score_summary',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  }, 


  {
    "step" :      56,
    "text" :      "All the words are tabulated with their multipliers!",
    "targets" :   [],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      57,
    "text" :      "You can navigate to the instructions page for a refresher on how to play - Tap the glowing help icon",
    "targets" :   ["help_icon"],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'help_icon',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },  


  {
    "step" :      58,
    "text" :      "You can adjust parameters on the settings page - Tap the glowing settings icon",
    "targets" :   ["settings_icon"],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'settings_icon',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },   

  {
    "step" :      59,
    "text" :      "And finally, you can exit the game or restart at any time - Tap the exit icon",
    "targets" :   ["exit_icon"],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': 'exit_icon',
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': false,     
  },                      


  {
    "step" :      60,
    "text" :      "",
    "targets" :   [],
    "points":     462,
    "words":      9,
    "newPoints":  0,
    "newWords":   0,
    "streak":     0,
    "crossword":  0,
    "complete":   true,
    "autoPlace":  false,
    "input":      null,
    "inputType":  null,
    'isTapped':   false,
    'isDrag':     false, //true,
    'dragSource': null, //'reserve_1',
    'tilesToRemove': [],
    'callbackTarget': null,
    'tilesInWord':  [],
    'isPaused':   true,
    'isGameStarted': true,
    'isGameEnded': true,         
  },

];


